language: node_js
node_js:
  - "8.3.0"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
after_script:
  - ./cc-test-reporter format-coverage -t lcov ./test/coverage/lcov.info
  - ./cc-test-reporter upload-coverage
