version: "3.2"
services:
  api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000"
  redis:
    build:
      context: .
      dockerfile: ./build/redis/Dockerfile
    ports:
      - "6379:6379"
