version: "3.2"
services:
  npr-api-node:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - npr-api-redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  npr-api-redis:
    image: "csampson/npr-db:latest"
