version: "3.2"
services:
  opr-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - opr-db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  opr-db:
    image: redislabs/redisearch:2.0.4
