version: "3.2"

services:
    web:
        image: csampson/opr-api-web:alpha
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        depends_on:
            - db
        ports:
            - 80:3000
        volumes:
             - db-socket:/var/run/redis
        environment:
            - APOLLO_ENGINE_KEY
    db:
        image: csampson/opr-api-db:alpha
        build: ./docker/redis
        sysctls:
            net.core.somaxconn: 512
        volumes:
             - db-socket:/var/run/redis

volumes:
  db-socket:
