version: "3.2"
services:
  openpublicradio-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - openpublicradio-db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  openpublicradio-db:
    image: "redislabs/redisearch:2.0.4"
