apiVersion: v1
kind: Service
metadata:
  name: npr-db-api
  labels:
    app: npr-db
spec:
  type: LoadBalancer
  selector:
    app: npr-db
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npr-db-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npr-db
  template:
    metadata:
      labels:
        app: npr-db
    spec:
      containers:
      - name: npr-db-api
        image: csampson/npr-db-api:latest
        env:
        - name: REDIS_HOST
          value: npr-db-redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 3000
      restartPolicy: Always
