apiVersion: v1
kind: Service
metadata:
  name: openpublicradio-api
  labels:
    app: openpublicradio
spec:
  type: LoadBalancer
  selector:
    app: openpublicradio
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpublicradio-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openpublicradio
  template:
    metadata:
      labels:
        app: openpublicradio
    spec:
      containers:
      - name: openpublicradio-api
        image: openpublicradio/api:0.0.1
        env:
        - name: REDIS_HOST
          value: "openpublicradio-db"
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 3000
      restartPolicy: Always
