apiVersion: v1
kind: Service
metadata:
  name: npr-api-node
  labels:
    app: npr-api
spec:
  type: LoadBalancer
  selector:
    app: npr-api
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npr-api-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npr-api
  template:
    metadata:
      labels:
        app: npr-api
    spec:
      containers:
      - name: npr-api-node
        image: csampson/npr-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          value: npr-api-redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 3000
      restartPolicy: Always
