apiVersion: v1
kind: Service
metadata:
  name: npr-api-redis
  labels:
    app: npr-api
spec:
  selector:
    app: npr-api
  ports:
  - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npr-api-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npr-api
  template:
    metadata:
      labels:
        app: npr-api
    spec:
      containers:
      - name: npr-api-redis
        image: csampson/npr-db:latest
        ports:
          - containerPort: 6379
