apiVersion: v1
kind: Service
metadata:
  name: openpublicradio-db
  labels:
    app: openpublicradio
spec:
  selector:
    app: openpublicradio
  ports:
  - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpublicradio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openpublicradio
  template:
    metadata:
      labels:
        app: openpublicradio
    spec:
      containers:
      - name: openpublicradio-db
        image: redislabs/redisearch:2.0.3
        ports:
          - containerPort: 6379
